name: "1 - Build & Create PR Develop"

on:
  push:
    branches:
      - "feature/**"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    name: Testes unitários
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven' # cache ~/.m2 automático

      - name: Run tests (maven)
        run: mvn -B -ntp test

      - name: Publicar relatórios (se falhar)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/*'

  create-auto-pull-request:
    name: Open PR to develop
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Open PR Develop
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: ${{ github.ref_name }}
          to-branch: develop
          repository-owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}